version: "3.9"

services:
  app:
    build: .
    container_name: inventario_pro
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:/app/data/inventario.db?mode=rwc
      - RUST_LOG=info
